// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package notify

import (
	"sync"
)

// Ensure, that NotifierMock does implement Notifier.
// If this is not the case, regenerate this file with moq.
var _ Notifier = &NotifierMock{}

// NotifierMock is a mock implementation of Notifier.
//
//	func TestSomethingThatUsesNotifier(t *testing.T) {
//
//		// make and configure a mocked Notifier
//		mockedNotifier := &NotifierMock{
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//			SendFunc: func(incident Incident) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedNotifier in code that requires Notifier
//		// and then make assertions.
//
//	}
type NotifierMock struct {
	// NameFunc mocks the Name method.
	NameFunc func() string

	// SendFunc mocks the Send method.
	SendFunc func(incident Incident) error

	// calls tracks calls to the methods.
	calls struct {
		// Name holds details about calls to the Name method.
		Name []struct {
		}
		// Send holds details about calls to the Send method.
		Send []struct {
			// Incident is the incident argument value.
			Incident Incident
		}
	}
	lockName sync.RWMutex
	lockSend sync.RWMutex
}

// Name calls NameFunc.
func (mock *NotifierMock) Name() string {
	if mock.NameFunc == nil {
		panic("NotifierMock.NameFunc: method is nil but Notifier.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedNotifier.NameCalls())
func (mock *NotifierMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// Send calls SendFunc.
func (mock *NotifierMock) Send(incident Incident) error {
	if mock.SendFunc == nil {
		panic("NotifierMock.SendFunc: method is nil but Notifier.Send was just called")
	}
	callInfo := struct {
		Incident Incident
	}{
		Incident: incident,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(incident)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedNotifier.SendCalls())
func (mock *NotifierMock) SendCalls() []struct {
	Incident Incident
} {
	var calls []struct {
		Incident Incident
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
