// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package syscontrol

import (
	"sync"
)

// Ensure, that ControllerMock does implement Controller.
// If this is not the case, regenerate this file with moq.
var _ Controller = &ControllerMock{}

// ControllerMock is a mock implementation of Controller.
//
//	func TestSomethingThatUsesController(t *testing.T) {
//
//		// make and configure a mocked Controller
//		mockedController := &ControllerMock{
//			SleepFunc: func() error {
//				panic("mock out the Sleep method")
//			},
//		}
//
//		// use mockedController in code that requires Controller
//		// and then make assertions.
//
//	}
type ControllerMock struct {
	// SleepFunc mocks the Sleep method.
	SleepFunc func() error

	// calls tracks calls to the methods.
	calls struct {
		// Sleep holds details about calls to the Sleep method.
		Sleep []struct {
		}
	}
	lockSleep sync.RWMutex
}

// Sleep calls SleepFunc.
func (mock *ControllerMock) Sleep() error {
	if mock.SleepFunc == nil {
		panic("ControllerMock.SleepFunc: method is nil but Controller.Sleep was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSleep.Lock()
	mock.calls.Sleep = append(mock.calls.Sleep, callInfo)
	mock.lockSleep.Unlock()
	return mock.SleepFunc()
}

// SleepCalls gets all the calls that were made to Sleep.
// Check the length with:
//
//	len(mockedController.SleepCalls())
func (mock *ControllerMock) SleepCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSleep.RLock()
	calls = mock.calls.Sleep
	mock.lockSleep.RUnlock()
	return calls
}
