// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package hardware

import (
	"sync"
)

// Ensure, that ReporterMock does implement Reporter.
// If this is not the case, regenerate this file with moq.
var _ Reporter = &ReporterMock{}

// ReporterMock is a mock implementation of Reporter.
//
//	func TestSomethingThatUsesReporter(t *testing.T) {
//
//		// make and configure a mocked Reporter
//		mockedReporter := &ReporterMock{
//			ShowFunc: func(components []string) error {
//				panic("mock out the Show method")
//			},
//		}
//
//		// use mockedReporter in code that requires Reporter
//		// and then make assertions.
//
//	}
type ReporterMock struct {
	// ShowFunc mocks the Show method.
	ShowFunc func(components []string) error

	// calls tracks calls to the methods.
	calls struct {
		// Show holds details about calls to the Show method.
		Show []struct {
			// Components is the components argument value.
			Components []string
		}
	}
	lockShow sync.RWMutex
}

// Show calls ShowFunc.
func (mock *ReporterMock) Show(components []string) error {
	if mock.ShowFunc == nil {
		panic("ReporterMock.ShowFunc: method is nil but Reporter.Show was just called")
	}
	callInfo := struct {
		Components []string
	}{
		Components: components,
	}
	mock.lockShow.Lock()
	mock.calls.Show = append(mock.calls.Show, callInfo)
	mock.lockShow.Unlock()
	return mock.ShowFunc(components)
}

// ShowCalls gets all the calls that were made to Show.
// Check the length with:
//
//	len(mockedReporter.ShowCalls())
func (mock *ReporterMock) ShowCalls() []struct {
	Components []string
} {
	var calls []struct {
		Components []string
	}
	mock.lockShow.RLock()
	calls = mock.calls.Show
	mock.lockShow.RUnlock()
	return calls
}
