// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package pkgmgr

import (
	"sync"
)

// Ensure, that ManagerMock does implement Manager.
// If this is not the case, regenerate this file with moq.
var _ Manager = &ManagerMock{}

// ManagerMock is a mock implementation of Manager.
//
//	func TestSomethingThatUsesManager(t *testing.T) {
//
//		// make and configure a mocked Manager
//		mockedManager := &ManagerMock{
//			CleanFunc: func(opts CleanOptions) error {
//				panic("mock out the Clean method")
//			},
//			InstalledFunc: func(opts InstalledOptions) error {
//				panic("mock out the Installed method")
//			},
//			PackagesFunc: func(opts PackageOptions) error {
//				panic("mock out the Packages method")
//			},
//			UpdateSystemFunc: func(opts UpdateOptions) error {
//				panic("mock out the UpdateSystem method")
//			},
//		}
//
//		// use mockedManager in code that requires Manager
//		// and then make assertions.
//
//	}
type ManagerMock struct {
	// CleanFunc mocks the Clean method.
	CleanFunc func(opts CleanOptions) error

	// InstalledFunc mocks the Installed method.
	InstalledFunc func(opts InstalledOptions) error

	// PackagesFunc mocks the Packages method.
	PackagesFunc func(opts PackageOptions) error

	// UpdateSystemFunc mocks the UpdateSystem method.
	UpdateSystemFunc func(opts UpdateOptions) error

	// calls tracks calls to the methods.
	calls struct {
		// Clean holds details about calls to the Clean method.
		Clean []struct {
			// Opts is the opts argument value.
			Opts CleanOptions
		}
		// Installed holds details about calls to the Installed method.
		Installed []struct {
			// Opts is the opts argument value.
			Opts InstalledOptions
		}
		// Packages holds details about calls to the Packages method.
		Packages []struct {
			// Opts is the opts argument value.
			Opts PackageOptions
		}
		// UpdateSystem holds details about calls to the UpdateSystem method.
		UpdateSystem []struct {
			// Opts is the opts argument value.
			Opts UpdateOptions
		}
	}
	lockClean        sync.RWMutex
	lockInstalled    sync.RWMutex
	lockPackages     sync.RWMutex
	lockUpdateSystem sync.RWMutex
}

// Clean calls CleanFunc.
func (mock *ManagerMock) Clean(opts CleanOptions) error {
	if mock.CleanFunc == nil {
		panic("ManagerMock.CleanFunc: method is nil but Manager.Clean was just called")
	}
	callInfo := struct {
		Opts CleanOptions
	}{
		Opts: opts,
	}
	mock.lockClean.Lock()
	mock.calls.Clean = append(mock.calls.Clean, callInfo)
	mock.lockClean.Unlock()
	return mock.CleanFunc(opts)
}

// CleanCalls gets all the calls that were made to Clean.
// Check the length with:
//
//	len(mockedManager.CleanCalls())
func (mock *ManagerMock) CleanCalls() []struct {
	Opts CleanOptions
} {
	var calls []struct {
		Opts CleanOptions
	}
	mock.lockClean.RLock()
	calls = mock.calls.Clean
	mock.lockClean.RUnlock()
	return calls
}

// Installed calls InstalledFunc.
func (mock *ManagerMock) Installed(opts InstalledOptions) error {
	if mock.InstalledFunc == nil {
		panic("ManagerMock.InstalledFunc: method is nil but Manager.Installed was just called")
	}
	callInfo := struct {
		Opts InstalledOptions
	}{
		Opts: opts,
	}
	mock.lockInstalled.Lock()
	mock.calls.Installed = append(mock.calls.Installed, callInfo)
	mock.lockInstalled.Unlock()
	return mock.InstalledFunc(opts)
}

// InstalledCalls gets all the calls that were made to Installed.
// Check the length with:
//
//	len(mockedManager.InstalledCalls())
func (mock *ManagerMock) InstalledCalls() []struct {
	Opts InstalledOptions
} {
	var calls []struct {
		Opts InstalledOptions
	}
	mock.lockInstalled.RLock()
	calls = mock.calls.Installed
	mock.lockInstalled.RUnlock()
	return calls
}

// Packages calls PackagesFunc.
func (mock *ManagerMock) Packages(opts PackageOptions) error {
	if mock.PackagesFunc == nil {
		panic("ManagerMock.PackagesFunc: method is nil but Manager.Packages was just called")
	}
	callInfo := struct {
		Opts PackageOptions
	}{
		Opts: opts,
	}
	mock.lockPackages.Lock()
	mock.calls.Packages = append(mock.calls.Packages, callInfo)
	mock.lockPackages.Unlock()
	return mock.PackagesFunc(opts)
}

// PackagesCalls gets all the calls that were made to Packages.
// Check the length with:
//
//	len(mockedManager.PackagesCalls())
func (mock *ManagerMock) PackagesCalls() []struct {
	Opts PackageOptions
} {
	var calls []struct {
		Opts PackageOptions
	}
	mock.lockPackages.RLock()
	calls = mock.calls.Packages
	mock.lockPackages.RUnlock()
	return calls
}

// UpdateSystem calls UpdateSystemFunc.
func (mock *ManagerMock) UpdateSystem(opts UpdateOptions) error {
	if mock.UpdateSystemFunc == nil {
		panic("ManagerMock.UpdateSystemFunc: method is nil but Manager.UpdateSystem was just called")
	}
	callInfo := struct {
		Opts UpdateOptions
	}{
		Opts: opts,
	}
	mock.lockUpdateSystem.Lock()
	mock.calls.UpdateSystem = append(mock.calls.UpdateSystem, callInfo)
	mock.lockUpdateSystem.Unlock()
	return mock.UpdateSystemFunc(opts)
}

// UpdateSystemCalls gets all the calls that were made to UpdateSystem.
// Check the length with:
//
//	len(mockedManager.UpdateSystemCalls())
func (mock *ManagerMock) UpdateSystemCalls() []struct {
	Opts UpdateOptions
} {
	var calls []struct {
		Opts UpdateOptions
	}
	mock.lockUpdateSystem.RLock()
	calls = mock.calls.UpdateSystem
	mock.lockUpdateSystem.RUnlock()
	return calls
}
