// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package pkgmgr

import (
	"sync"

	"github.com/jyablonski/arc/internal/pacman"
)

// Ensure, that pacmanOpsMock does implement pacmanOps.
// If this is not the case, regenerate this file with moq.
var _ pacmanOps = &pacmanOpsMock{}

// pacmanOpsMock is a mock implementation of pacmanOps.
//
//	func TestSomethingThatUsespacmanOps(t *testing.T) {
//
//		// make and configure a mocked pacmanOps
//		mockedpacmanOps := &pacmanOpsMock{
//			CheckPacmanAvailableFunc: func() error {
//				panic("mock out the CheckPacmanAvailable method")
//			},
//			GetCacheSizeFunc: func() (string, error) {
//				panic("mock out the GetCacheSize method")
//			},
//			GetExplicitlyInstalledFunc: func() ([]string, error) {
//				panic("mock out the GetExplicitlyInstalled method")
//			},
//			GetExplicitlyInstalledCountFunc: func() (int, error) {
//				panic("mock out the GetExplicitlyInstalledCount method")
//			},
//			GetForeignPackageCountFunc: func() (int, error) {
//				panic("mock out the GetForeignPackageCount method")
//			},
//			GetForeignPackagesFunc: func() ([]string, error) {
//				panic("mock out the GetForeignPackages method")
//			},
//			GetLargestPackagesFunc: func(topN int) ([]pacman.PackageInfo, error) {
//				panic("mock out the GetLargestPackages method")
//			},
//			GetOrphanedPackagesFunc: func() ([]string, error) {
//				panic("mock out the GetOrphanedPackages method")
//			},
//			GetPackageCountFunc: func() (int, error) {
//				panic("mock out the GetPackageCount method")
//			},
//			GetRecentlyInstalledCountFunc: func(days int) (int, error) {
//				panic("mock out the GetRecentlyInstalledCount method")
//			},
//			GetTotalInstalledSizeFunc: func() (float64, error) {
//				panic("mock out the GetTotalInstalledSize method")
//			},
//		}
//
//		// use mockedpacmanOps in code that requires pacmanOps
//		// and then make assertions.
//
//	}
type pacmanOpsMock struct {
	// CheckPacmanAvailableFunc mocks the CheckPacmanAvailable method.
	CheckPacmanAvailableFunc func() error

	// GetCacheSizeFunc mocks the GetCacheSize method.
	GetCacheSizeFunc func() (string, error)

	// GetExplicitlyInstalledFunc mocks the GetExplicitlyInstalled method.
	GetExplicitlyInstalledFunc func() ([]string, error)

	// GetExplicitlyInstalledCountFunc mocks the GetExplicitlyInstalledCount method.
	GetExplicitlyInstalledCountFunc func() (int, error)

	// GetForeignPackageCountFunc mocks the GetForeignPackageCount method.
	GetForeignPackageCountFunc func() (int, error)

	// GetForeignPackagesFunc mocks the GetForeignPackages method.
	GetForeignPackagesFunc func() ([]string, error)

	// GetLargestPackagesFunc mocks the GetLargestPackages method.
	GetLargestPackagesFunc func(topN int) ([]pacman.PackageInfo, error)

	// GetOrphanedPackagesFunc mocks the GetOrphanedPackages method.
	GetOrphanedPackagesFunc func() ([]string, error)

	// GetPackageCountFunc mocks the GetPackageCount method.
	GetPackageCountFunc func() (int, error)

	// GetRecentlyInstalledCountFunc mocks the GetRecentlyInstalledCount method.
	GetRecentlyInstalledCountFunc func(days int) (int, error)

	// GetTotalInstalledSizeFunc mocks the GetTotalInstalledSize method.
	GetTotalInstalledSizeFunc func() (float64, error)

	// calls tracks calls to the methods.
	calls struct {
		// CheckPacmanAvailable holds details about calls to the CheckPacmanAvailable method.
		CheckPacmanAvailable []struct {
		}
		// GetCacheSize holds details about calls to the GetCacheSize method.
		GetCacheSize []struct {
		}
		// GetExplicitlyInstalled holds details about calls to the GetExplicitlyInstalled method.
		GetExplicitlyInstalled []struct {
		}
		// GetExplicitlyInstalledCount holds details about calls to the GetExplicitlyInstalledCount method.
		GetExplicitlyInstalledCount []struct {
		}
		// GetForeignPackageCount holds details about calls to the GetForeignPackageCount method.
		GetForeignPackageCount []struct {
		}
		// GetForeignPackages holds details about calls to the GetForeignPackages method.
		GetForeignPackages []struct {
		}
		// GetLargestPackages holds details about calls to the GetLargestPackages method.
		GetLargestPackages []struct {
			// TopN is the topN argument value.
			TopN int
		}
		// GetOrphanedPackages holds details about calls to the GetOrphanedPackages method.
		GetOrphanedPackages []struct {
		}
		// GetPackageCount holds details about calls to the GetPackageCount method.
		GetPackageCount []struct {
		}
		// GetRecentlyInstalledCount holds details about calls to the GetRecentlyInstalledCount method.
		GetRecentlyInstalledCount []struct {
			// Days is the days argument value.
			Days int
		}
		// GetTotalInstalledSize holds details about calls to the GetTotalInstalledSize method.
		GetTotalInstalledSize []struct {
		}
	}
	lockCheckPacmanAvailable        sync.RWMutex
	lockGetCacheSize                sync.RWMutex
	lockGetExplicitlyInstalled      sync.RWMutex
	lockGetExplicitlyInstalledCount sync.RWMutex
	lockGetForeignPackageCount      sync.RWMutex
	lockGetForeignPackages          sync.RWMutex
	lockGetLargestPackages          sync.RWMutex
	lockGetOrphanedPackages         sync.RWMutex
	lockGetPackageCount             sync.RWMutex
	lockGetRecentlyInstalledCount   sync.RWMutex
	lockGetTotalInstalledSize       sync.RWMutex
}

// CheckPacmanAvailable calls CheckPacmanAvailableFunc.
func (mock *pacmanOpsMock) CheckPacmanAvailable() error {
	if mock.CheckPacmanAvailableFunc == nil {
		panic("pacmanOpsMock.CheckPacmanAvailableFunc: method is nil but pacmanOps.CheckPacmanAvailable was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCheckPacmanAvailable.Lock()
	mock.calls.CheckPacmanAvailable = append(mock.calls.CheckPacmanAvailable, callInfo)
	mock.lockCheckPacmanAvailable.Unlock()
	return mock.CheckPacmanAvailableFunc()
}

// CheckPacmanAvailableCalls gets all the calls that were made to CheckPacmanAvailable.
// Check the length with:
//
//	len(mockedpacmanOps.CheckPacmanAvailableCalls())
func (mock *pacmanOpsMock) CheckPacmanAvailableCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCheckPacmanAvailable.RLock()
	calls = mock.calls.CheckPacmanAvailable
	mock.lockCheckPacmanAvailable.RUnlock()
	return calls
}

// GetCacheSize calls GetCacheSizeFunc.
func (mock *pacmanOpsMock) GetCacheSize() (string, error) {
	if mock.GetCacheSizeFunc == nil {
		panic("pacmanOpsMock.GetCacheSizeFunc: method is nil but pacmanOps.GetCacheSize was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetCacheSize.Lock()
	mock.calls.GetCacheSize = append(mock.calls.GetCacheSize, callInfo)
	mock.lockGetCacheSize.Unlock()
	return mock.GetCacheSizeFunc()
}

// GetCacheSizeCalls gets all the calls that were made to GetCacheSize.
// Check the length with:
//
//	len(mockedpacmanOps.GetCacheSizeCalls())
func (mock *pacmanOpsMock) GetCacheSizeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetCacheSize.RLock()
	calls = mock.calls.GetCacheSize
	mock.lockGetCacheSize.RUnlock()
	return calls
}

// GetExplicitlyInstalled calls GetExplicitlyInstalledFunc.
func (mock *pacmanOpsMock) GetExplicitlyInstalled() ([]string, error) {
	if mock.GetExplicitlyInstalledFunc == nil {
		panic("pacmanOpsMock.GetExplicitlyInstalledFunc: method is nil but pacmanOps.GetExplicitlyInstalled was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetExplicitlyInstalled.Lock()
	mock.calls.GetExplicitlyInstalled = append(mock.calls.GetExplicitlyInstalled, callInfo)
	mock.lockGetExplicitlyInstalled.Unlock()
	return mock.GetExplicitlyInstalledFunc()
}

// GetExplicitlyInstalledCalls gets all the calls that were made to GetExplicitlyInstalled.
// Check the length with:
//
//	len(mockedpacmanOps.GetExplicitlyInstalledCalls())
func (mock *pacmanOpsMock) GetExplicitlyInstalledCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetExplicitlyInstalled.RLock()
	calls = mock.calls.GetExplicitlyInstalled
	mock.lockGetExplicitlyInstalled.RUnlock()
	return calls
}

// GetExplicitlyInstalledCount calls GetExplicitlyInstalledCountFunc.
func (mock *pacmanOpsMock) GetExplicitlyInstalledCount() (int, error) {
	if mock.GetExplicitlyInstalledCountFunc == nil {
		panic("pacmanOpsMock.GetExplicitlyInstalledCountFunc: method is nil but pacmanOps.GetExplicitlyInstalledCount was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetExplicitlyInstalledCount.Lock()
	mock.calls.GetExplicitlyInstalledCount = append(mock.calls.GetExplicitlyInstalledCount, callInfo)
	mock.lockGetExplicitlyInstalledCount.Unlock()
	return mock.GetExplicitlyInstalledCountFunc()
}

// GetExplicitlyInstalledCountCalls gets all the calls that were made to GetExplicitlyInstalledCount.
// Check the length with:
//
//	len(mockedpacmanOps.GetExplicitlyInstalledCountCalls())
func (mock *pacmanOpsMock) GetExplicitlyInstalledCountCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetExplicitlyInstalledCount.RLock()
	calls = mock.calls.GetExplicitlyInstalledCount
	mock.lockGetExplicitlyInstalledCount.RUnlock()
	return calls
}

// GetForeignPackageCount calls GetForeignPackageCountFunc.
func (mock *pacmanOpsMock) GetForeignPackageCount() (int, error) {
	if mock.GetForeignPackageCountFunc == nil {
		panic("pacmanOpsMock.GetForeignPackageCountFunc: method is nil but pacmanOps.GetForeignPackageCount was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetForeignPackageCount.Lock()
	mock.calls.GetForeignPackageCount = append(mock.calls.GetForeignPackageCount, callInfo)
	mock.lockGetForeignPackageCount.Unlock()
	return mock.GetForeignPackageCountFunc()
}

// GetForeignPackageCountCalls gets all the calls that were made to GetForeignPackageCount.
// Check the length with:
//
//	len(mockedpacmanOps.GetForeignPackageCountCalls())
func (mock *pacmanOpsMock) GetForeignPackageCountCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetForeignPackageCount.RLock()
	calls = mock.calls.GetForeignPackageCount
	mock.lockGetForeignPackageCount.RUnlock()
	return calls
}

// GetForeignPackages calls GetForeignPackagesFunc.
func (mock *pacmanOpsMock) GetForeignPackages() ([]string, error) {
	if mock.GetForeignPackagesFunc == nil {
		panic("pacmanOpsMock.GetForeignPackagesFunc: method is nil but pacmanOps.GetForeignPackages was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetForeignPackages.Lock()
	mock.calls.GetForeignPackages = append(mock.calls.GetForeignPackages, callInfo)
	mock.lockGetForeignPackages.Unlock()
	return mock.GetForeignPackagesFunc()
}

// GetForeignPackagesCalls gets all the calls that were made to GetForeignPackages.
// Check the length with:
//
//	len(mockedpacmanOps.GetForeignPackagesCalls())
func (mock *pacmanOpsMock) GetForeignPackagesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetForeignPackages.RLock()
	calls = mock.calls.GetForeignPackages
	mock.lockGetForeignPackages.RUnlock()
	return calls
}

// GetLargestPackages calls GetLargestPackagesFunc.
func (mock *pacmanOpsMock) GetLargestPackages(topN int) ([]pacman.PackageInfo, error) {
	if mock.GetLargestPackagesFunc == nil {
		panic("pacmanOpsMock.GetLargestPackagesFunc: method is nil but pacmanOps.GetLargestPackages was just called")
	}
	callInfo := struct {
		TopN int
	}{
		TopN: topN,
	}
	mock.lockGetLargestPackages.Lock()
	mock.calls.GetLargestPackages = append(mock.calls.GetLargestPackages, callInfo)
	mock.lockGetLargestPackages.Unlock()
	return mock.GetLargestPackagesFunc(topN)
}

// GetLargestPackagesCalls gets all the calls that were made to GetLargestPackages.
// Check the length with:
//
//	len(mockedpacmanOps.GetLargestPackagesCalls())
func (mock *pacmanOpsMock) GetLargestPackagesCalls() []struct {
	TopN int
} {
	var calls []struct {
		TopN int
	}
	mock.lockGetLargestPackages.RLock()
	calls = mock.calls.GetLargestPackages
	mock.lockGetLargestPackages.RUnlock()
	return calls
}

// GetOrphanedPackages calls GetOrphanedPackagesFunc.
func (mock *pacmanOpsMock) GetOrphanedPackages() ([]string, error) {
	if mock.GetOrphanedPackagesFunc == nil {
		panic("pacmanOpsMock.GetOrphanedPackagesFunc: method is nil but pacmanOps.GetOrphanedPackages was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetOrphanedPackages.Lock()
	mock.calls.GetOrphanedPackages = append(mock.calls.GetOrphanedPackages, callInfo)
	mock.lockGetOrphanedPackages.Unlock()
	return mock.GetOrphanedPackagesFunc()
}

// GetOrphanedPackagesCalls gets all the calls that were made to GetOrphanedPackages.
// Check the length with:
//
//	len(mockedpacmanOps.GetOrphanedPackagesCalls())
func (mock *pacmanOpsMock) GetOrphanedPackagesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetOrphanedPackages.RLock()
	calls = mock.calls.GetOrphanedPackages
	mock.lockGetOrphanedPackages.RUnlock()
	return calls
}

// GetPackageCount calls GetPackageCountFunc.
func (mock *pacmanOpsMock) GetPackageCount() (int, error) {
	if mock.GetPackageCountFunc == nil {
		panic("pacmanOpsMock.GetPackageCountFunc: method is nil but pacmanOps.GetPackageCount was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetPackageCount.Lock()
	mock.calls.GetPackageCount = append(mock.calls.GetPackageCount, callInfo)
	mock.lockGetPackageCount.Unlock()
	return mock.GetPackageCountFunc()
}

// GetPackageCountCalls gets all the calls that were made to GetPackageCount.
// Check the length with:
//
//	len(mockedpacmanOps.GetPackageCountCalls())
func (mock *pacmanOpsMock) GetPackageCountCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetPackageCount.RLock()
	calls = mock.calls.GetPackageCount
	mock.lockGetPackageCount.RUnlock()
	return calls
}

// GetRecentlyInstalledCount calls GetRecentlyInstalledCountFunc.
func (mock *pacmanOpsMock) GetRecentlyInstalledCount(days int) (int, error) {
	if mock.GetRecentlyInstalledCountFunc == nil {
		panic("pacmanOpsMock.GetRecentlyInstalledCountFunc: method is nil but pacmanOps.GetRecentlyInstalledCount was just called")
	}
	callInfo := struct {
		Days int
	}{
		Days: days,
	}
	mock.lockGetRecentlyInstalledCount.Lock()
	mock.calls.GetRecentlyInstalledCount = append(mock.calls.GetRecentlyInstalledCount, callInfo)
	mock.lockGetRecentlyInstalledCount.Unlock()
	return mock.GetRecentlyInstalledCountFunc(days)
}

// GetRecentlyInstalledCountCalls gets all the calls that were made to GetRecentlyInstalledCount.
// Check the length with:
//
//	len(mockedpacmanOps.GetRecentlyInstalledCountCalls())
func (mock *pacmanOpsMock) GetRecentlyInstalledCountCalls() []struct {
	Days int
} {
	var calls []struct {
		Days int
	}
	mock.lockGetRecentlyInstalledCount.RLock()
	calls = mock.calls.GetRecentlyInstalledCount
	mock.lockGetRecentlyInstalledCount.RUnlock()
	return calls
}

// GetTotalInstalledSize calls GetTotalInstalledSizeFunc.
func (mock *pacmanOpsMock) GetTotalInstalledSize() (float64, error) {
	if mock.GetTotalInstalledSizeFunc == nil {
		panic("pacmanOpsMock.GetTotalInstalledSizeFunc: method is nil but pacmanOps.GetTotalInstalledSize was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetTotalInstalledSize.Lock()
	mock.calls.GetTotalInstalledSize = append(mock.calls.GetTotalInstalledSize, callInfo)
	mock.lockGetTotalInstalledSize.Unlock()
	return mock.GetTotalInstalledSizeFunc()
}

// GetTotalInstalledSizeCalls gets all the calls that were made to GetTotalInstalledSize.
// Check the length with:
//
//	len(mockedpacmanOps.GetTotalInstalledSizeCalls())
func (mock *pacmanOpsMock) GetTotalInstalledSizeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetTotalInstalledSize.RLock()
	calls = mock.calls.GetTotalInstalledSize
	mock.lockGetTotalInstalledSize.RUnlock()
	return calls
}
