// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package boundary

import (
	"sync"
)

// Ensure, that ShellRunnerMock does implement ShellRunner.
// If this is not the case, regenerate this file with moq.
var _ ShellRunner = &ShellRunnerMock{}

// ShellRunnerMock is a mock implementation of ShellRunner.
//
//	func TestSomethingThatUsesShellRunner(t *testing.T) {
//
//		// make and configure a mocked ShellRunner
//		mockedShellRunner := &ShellRunnerMock{
//			CommandExistsFunc: func(name string) bool {
//				panic("mock out the CommandExists method")
//			},
//			RunFunc: func(name string, args ...string) (string, error) {
//				panic("mock out the Run method")
//			},
//			RunInteractiveFunc: func(name string, args ...string) error {
//				panic("mock out the RunInteractive method")
//			},
//			RunSudoFunc: func(name string, args ...string) (string, error) {
//				panic("mock out the RunSudo method")
//			},
//		}
//
//		// use mockedShellRunner in code that requires ShellRunner
//		// and then make assertions.
//
//	}
type ShellRunnerMock struct {
	// CommandExistsFunc mocks the CommandExists method.
	CommandExistsFunc func(name string) bool

	// RunFunc mocks the Run method.
	RunFunc func(name string, args ...string) (string, error)

	// RunInteractiveFunc mocks the RunInteractive method.
	RunInteractiveFunc func(name string, args ...string) error

	// RunSudoFunc mocks the RunSudo method.
	RunSudoFunc func(name string, args ...string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// CommandExists holds details about calls to the CommandExists method.
		CommandExists []struct {
			// Name is the name argument value.
			Name string
		}
		// Run holds details about calls to the Run method.
		Run []struct {
			// Name is the name argument value.
			Name string
			// Args is the args argument value.
			Args []string
		}
		// RunInteractive holds details about calls to the RunInteractive method.
		RunInteractive []struct {
			// Name is the name argument value.
			Name string
			// Args is the args argument value.
			Args []string
		}
		// RunSudo holds details about calls to the RunSudo method.
		RunSudo []struct {
			// Name is the name argument value.
			Name string
			// Args is the args argument value.
			Args []string
		}
	}
	lockCommandExists  sync.RWMutex
	lockRun            sync.RWMutex
	lockRunInteractive sync.RWMutex
	lockRunSudo        sync.RWMutex
}

// CommandExists calls CommandExistsFunc.
func (mock *ShellRunnerMock) CommandExists(name string) bool {
	if mock.CommandExistsFunc == nil {
		panic("ShellRunnerMock.CommandExistsFunc: method is nil but ShellRunner.CommandExists was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockCommandExists.Lock()
	mock.calls.CommandExists = append(mock.calls.CommandExists, callInfo)
	mock.lockCommandExists.Unlock()
	return mock.CommandExistsFunc(name)
}

// CommandExistsCalls gets all the calls that were made to CommandExists.
// Check the length with:
//
//	len(mockedShellRunner.CommandExistsCalls())
func (mock *ShellRunnerMock) CommandExistsCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockCommandExists.RLock()
	calls = mock.calls.CommandExists
	mock.lockCommandExists.RUnlock()
	return calls
}

// Run calls RunFunc.
func (mock *ShellRunnerMock) Run(name string, args ...string) (string, error) {
	if mock.RunFunc == nil {
		panic("ShellRunnerMock.RunFunc: method is nil but ShellRunner.Run was just called")
	}
	callInfo := struct {
		Name string
		Args []string
	}{
		Name: name,
		Args: args,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(name, args...)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedShellRunner.RunCalls())
func (mock *ShellRunnerMock) RunCalls() []struct {
	Name string
	Args []string
} {
	var calls []struct {
		Name string
		Args []string
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}

// RunInteractive calls RunInteractiveFunc.
func (mock *ShellRunnerMock) RunInteractive(name string, args ...string) error {
	if mock.RunInteractiveFunc == nil {
		panic("ShellRunnerMock.RunInteractiveFunc: method is nil but ShellRunner.RunInteractive was just called")
	}
	callInfo := struct {
		Name string
		Args []string
	}{
		Name: name,
		Args: args,
	}
	mock.lockRunInteractive.Lock()
	mock.calls.RunInteractive = append(mock.calls.RunInteractive, callInfo)
	mock.lockRunInteractive.Unlock()
	return mock.RunInteractiveFunc(name, args...)
}

// RunInteractiveCalls gets all the calls that were made to RunInteractive.
// Check the length with:
//
//	len(mockedShellRunner.RunInteractiveCalls())
func (mock *ShellRunnerMock) RunInteractiveCalls() []struct {
	Name string
	Args []string
} {
	var calls []struct {
		Name string
		Args []string
	}
	mock.lockRunInteractive.RLock()
	calls = mock.calls.RunInteractive
	mock.lockRunInteractive.RUnlock()
	return calls
}

// RunSudo calls RunSudoFunc.
func (mock *ShellRunnerMock) RunSudo(name string, args ...string) (string, error) {
	if mock.RunSudoFunc == nil {
		panic("ShellRunnerMock.RunSudoFunc: method is nil but ShellRunner.RunSudo was just called")
	}
	callInfo := struct {
		Name string
		Args []string
	}{
		Name: name,
		Args: args,
	}
	mock.lockRunSudo.Lock()
	mock.calls.RunSudo = append(mock.calls.RunSudo, callInfo)
	mock.lockRunSudo.Unlock()
	return mock.RunSudoFunc(name, args...)
}

// RunSudoCalls gets all the calls that were made to RunSudo.
// Check the length with:
//
//	len(mockedShellRunner.RunSudoCalls())
func (mock *ShellRunnerMock) RunSudoCalls() []struct {
	Name string
	Args []string
} {
	var calls []struct {
		Name string
		Args []string
	}
	mock.lockRunSudo.RLock()
	calls = mock.calls.RunSudo
	mock.lockRunSudo.RUnlock()
	return calls
}
