// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ai

import (
	"context"
	"sync"
)

// Ensure, that HealthCheckerMock does implement HealthChecker.
// If this is not the case, regenerate this file with moq.
var _ HealthChecker = &HealthCheckerMock{}

// HealthCheckerMock is a mock implementation of HealthChecker.
//
//	func TestSomethingThatUsesHealthChecker(t *testing.T) {
//
//		// make and configure a mocked HealthChecker
//		mockedHealthChecker := &HealthCheckerMock{
//			HealthFunc: func(ctx context.Context) []HealthCheck {
//				panic("mock out the Health method")
//			},
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//		}
//
//		// use mockedHealthChecker in code that requires HealthChecker
//		// and then make assertions.
//
//	}
type HealthCheckerMock struct {
	// HealthFunc mocks the Health method.
	HealthFunc func(ctx context.Context) []HealthCheck

	// NameFunc mocks the Name method.
	NameFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Health holds details about calls to the Health method.
		Health []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
	}
	lockHealth sync.RWMutex
	lockName   sync.RWMutex
}

// Health calls HealthFunc.
func (mock *HealthCheckerMock) Health(ctx context.Context) []HealthCheck {
	if mock.HealthFunc == nil {
		panic("HealthCheckerMock.HealthFunc: method is nil but HealthChecker.Health was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockHealth.Lock()
	mock.calls.Health = append(mock.calls.Health, callInfo)
	mock.lockHealth.Unlock()
	return mock.HealthFunc(ctx)
}

// HealthCalls gets all the calls that were made to Health.
// Check the length with:
//
//	len(mockedHealthChecker.HealthCalls())
func (mock *HealthCheckerMock) HealthCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockHealth.RLock()
	calls = mock.calls.Health
	mock.lockHealth.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *HealthCheckerMock) Name() string {
	if mock.NameFunc == nil {
		panic("HealthCheckerMock.NameFunc: method is nil but HealthChecker.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedHealthChecker.NameCalls())
func (mock *HealthCheckerMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}
