// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ai

import (
	"context"
	"sync"
)

// Ensure, that HistoryProviderMock does implement HistoryProvider.
// If this is not the case, regenerate this file with moq.
var _ HistoryProvider = &HistoryProviderMock{}

// HistoryProviderMock is a mock implementation of HistoryProvider.
//
//	func TestSomethingThatUsesHistoryProvider(t *testing.T) {
//
//		// make and configure a mocked HistoryProvider
//		mockedHistoryProvider := &HistoryProviderMock{
//			LocalUsageFunc: func(ctx context.Context, opts HistoryOptions) ([]TokenRecord, error) {
//				panic("mock out the LocalUsage method")
//			},
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//		}
//
//		// use mockedHistoryProvider in code that requires HistoryProvider
//		// and then make assertions.
//
//	}
type HistoryProviderMock struct {
	// LocalUsageFunc mocks the LocalUsage method.
	LocalUsageFunc func(ctx context.Context, opts HistoryOptions) ([]TokenRecord, error)

	// NameFunc mocks the Name method.
	NameFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// LocalUsage holds details about calls to the LocalUsage method.
		LocalUsage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts HistoryOptions
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
	}
	lockLocalUsage sync.RWMutex
	lockName       sync.RWMutex
}

// LocalUsage calls LocalUsageFunc.
func (mock *HistoryProviderMock) LocalUsage(ctx context.Context, opts HistoryOptions) ([]TokenRecord, error) {
	if mock.LocalUsageFunc == nil {
		panic("HistoryProviderMock.LocalUsageFunc: method is nil but HistoryProvider.LocalUsage was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts HistoryOptions
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockLocalUsage.Lock()
	mock.calls.LocalUsage = append(mock.calls.LocalUsage, callInfo)
	mock.lockLocalUsage.Unlock()
	return mock.LocalUsageFunc(ctx, opts)
}

// LocalUsageCalls gets all the calls that were made to LocalUsage.
// Check the length with:
//
//	len(mockedHistoryProvider.LocalUsageCalls())
func (mock *HistoryProviderMock) LocalUsageCalls() []struct {
	Ctx  context.Context
	Opts HistoryOptions
} {
	var calls []struct {
		Ctx  context.Context
		Opts HistoryOptions
	}
	mock.lockLocalUsage.RLock()
	calls = mock.calls.LocalUsage
	mock.lockLocalUsage.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *HistoryProviderMock) Name() string {
	if mock.NameFunc == nil {
		panic("HistoryProviderMock.NameFunc: method is nil but HistoryProvider.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedHistoryProvider.NameCalls())
func (mock *HistoryProviderMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}
