// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ai

import (
	"context"
	"sync"
)

// Ensure, that ProviderMock does implement Provider.
// If this is not the case, regenerate this file with moq.
var _ Provider = &ProviderMock{}

// ProviderMock is a mock implementation of Provider.
//
//	func TestSomethingThatUsesProvider(t *testing.T) {
//
//		// make and configure a mocked Provider
//		mockedProvider := &ProviderMock{
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//			UsageFunc: func(ctx context.Context) (UsageReport, error) {
//				panic("mock out the Usage method")
//			},
//		}
//
//		// use mockedProvider in code that requires Provider
//		// and then make assertions.
//
//	}
type ProviderMock struct {
	// NameFunc mocks the Name method.
	NameFunc func() string

	// UsageFunc mocks the Usage method.
	UsageFunc func(ctx context.Context) (UsageReport, error)

	// calls tracks calls to the methods.
	calls struct {
		// Name holds details about calls to the Name method.
		Name []struct {
		}
		// Usage holds details about calls to the Usage method.
		Usage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockName  sync.RWMutex
	lockUsage sync.RWMutex
}

// Name calls NameFunc.
func (mock *ProviderMock) Name() string {
	if mock.NameFunc == nil {
		panic("ProviderMock.NameFunc: method is nil but Provider.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedProvider.NameCalls())
func (mock *ProviderMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// Usage calls UsageFunc.
func (mock *ProviderMock) Usage(ctx context.Context) (UsageReport, error) {
	if mock.UsageFunc == nil {
		panic("ProviderMock.UsageFunc: method is nil but Provider.Usage was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockUsage.Lock()
	mock.calls.Usage = append(mock.calls.Usage, callInfo)
	mock.lockUsage.Unlock()
	return mock.UsageFunc(ctx)
}

// UsageCalls gets all the calls that were made to Usage.
// Check the length with:
//
//	len(mockedProvider.UsageCalls())
func (mock *ProviderMock) UsageCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockUsage.RLock()
	calls = mock.calls.Usage
	mock.lockUsage.RUnlock()
	return calls
}
