// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ai

import (
	"context"
	"sync"
)

// Ensure, that SessionProviderMock does implement SessionProvider.
// If this is not the case, regenerate this file with moq.
var _ SessionProvider = &SessionProviderMock{}

// SessionProviderMock is a mock implementation of SessionProvider.
//
//	func TestSomethingThatUsesSessionProvider(t *testing.T) {
//
//		// make and configure a mocked SessionProvider
//		mockedSessionProvider := &SessionProviderMock{
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//			SessionsFunc: func(ctx context.Context) ([]SessionSummary, error) {
//				panic("mock out the Sessions method")
//			},
//		}
//
//		// use mockedSessionProvider in code that requires SessionProvider
//		// and then make assertions.
//
//	}
type SessionProviderMock struct {
	// NameFunc mocks the Name method.
	NameFunc func() string

	// SessionsFunc mocks the Sessions method.
	SessionsFunc func(ctx context.Context) ([]SessionSummary, error)

	// calls tracks calls to the methods.
	calls struct {
		// Name holds details about calls to the Name method.
		Name []struct {
		}
		// Sessions holds details about calls to the Sessions method.
		Sessions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockName     sync.RWMutex
	lockSessions sync.RWMutex
}

// Name calls NameFunc.
func (mock *SessionProviderMock) Name() string {
	if mock.NameFunc == nil {
		panic("SessionProviderMock.NameFunc: method is nil but SessionProvider.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedSessionProvider.NameCalls())
func (mock *SessionProviderMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// Sessions calls SessionsFunc.
func (mock *SessionProviderMock) Sessions(ctx context.Context) ([]SessionSummary, error) {
	if mock.SessionsFunc == nil {
		panic("SessionProviderMock.SessionsFunc: method is nil but SessionProvider.Sessions was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockSessions.Lock()
	mock.calls.Sessions = append(mock.calls.Sessions, callInfo)
	mock.lockSessions.Unlock()
	return mock.SessionsFunc(ctx)
}

// SessionsCalls gets all the calls that were made to Sessions.
// Check the length with:
//
//	len(mockedSessionProvider.SessionsCalls())
func (mock *SessionProviderMock) SessionsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockSessions.RLock()
	calls = mock.calls.Sessions
	mock.lockSessions.RUnlock()
	return calls
}
